### PR TITLE
Generic Template: image_aspect_ratio supported

### PR DESCRIPTION
**Pull request by anton-nayshtut**
For more info see [1].

[1] https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic

### CODE REVIEW

**Comment by kimwz** [comment]
@anton-nayshtut thank you for your continued care and updates. the time I can check is limited, so if you want, I think it would be better to manage it together. I've given you permission. 

if you don't want it. comment me here.

**Comment by anton-nayshtut** [comment]
@kimwz Thank you!

Could you please elaborate on how to release a new version? Is committing the CHANGELOG and __init__.py changes (like in bc103e3) enough? And, if not, what are the extra work to be done?

**Comment by kimwz** [comment]
@anton-nayshtut Thank you. Finally, there is a step to upload to PYPI for the users to use like 'pip install fbmq'. please let me know your pypi userid. then I will register your id as a maintainer on this project on PYPI

**Comment by anton-nayshtut** [comment]
@kimwz 

My PYPI userid is tonynays.

Thanks again!

**Comment by kimwz** [comment]
@anton-nayshtut Now, you can upload to PYPI.
```
python setup.py sdist upload
```

**Comment by anton-nayshtut** [comment]
@kimwz Thanks!

**Comment by anton-nayshtut** [comment]
It seems that 
`python setup.py sdist upload`
doesn't work anymore.

I succeeded to release following the procedure described [here](https://stackoverflow.com/a/45209514).

Hope it's OK.

**Comment by kimwz** [comment]
cool. no problem. thanks.

**Pull request merged**
