### PR TITLE
Messenger Code API supported

### PR DESCRIPTION
**Pull request by anton-nayshtut**
For more info see [1]

[1] https://developers.facebook.com/docs/messenger-platform/messenger-code

### CODE REVIEW

**Comment by anton-nayshtut** [comment]
Despite the fact that the patch decreases coverage, I can hardly see any way to unit test it.

Please advise.

**Comment by anton-nayshtut** [comment]
Any news with this, guys?

**Comment by anton-nayshtut** [comment]
See my comment above (https://github.com/conbus/fbmq/pull/27#issuecomment-321546963)

**Comment by kimwz** [comment]
thanks. I'll check and merge.

**Pull request merged**
